export const translations = {
  English: {
    // Brand
    brandName: "CyberSentinel AI",
    tagline: "Stay One Step Ahead of Recruitment Scams",
    subheading: "Verify jobs, internships, recruiter emails, websites and QR codes using AI before sharing your personal information.",
    getStarted: "Get Started",
    verifyNow: "Verify Now",
    
    // Sidebar
    navDashboard: "Dashboard",
    navJobVerify: "Job Verification",
    navWebVerify: "Website Verification",
    navEmailVerify: "Email Verification",
    navQRVerify: "QR Verification",
    navAssistant: "AI Assistant",
    navReports: "Reports",
    navAnalytics: "Analytics",
    navNotifications: "Notifications",
    navProfile: "Profile",
    navSettings: "Settings",
    navLogout: "Logout",
    
    // Stats
    statVerified: "Opportunities Verified",
    statAccuracy: "AI Detection Accuracy",
    statProtected: "Students Protected",
    
    // Dashboard Card Labels
    cardTotalScans: "Total Scans",
    cardSafeReports: "Safe Reports",
    cardHighRisk: "High Risk Reports",
    cardConfidence: "AI Avg Confidence",
    cardRecentActivity: "Recent Activity",
    cardScamAlerts: "Latest Scam Alerts",
    
    // Common Actions / Fields
    analyze: "Analyze Content",
    analyzing: "Analyzing...",
    riskScore: "Risk Score",
    threatLevel: "Threat Level",
    threatCategory: "Scam Category",
    reasons: "Why is this flagged?",
    recommendations: "Safety Actions Required",
    summary: "AI Summary",
    confidence: "Detection Confidence",
    safe: "Safe",
    mediumRisk: "Medium Risk",
    highRisk: "High Risk",
    
    // Modules Specifics
    jobDescPlaceholder: "Paste Job Description or Internship Offer Letter details here...",
    webUrlPlaceholder: "Paste company website URL (e.g., https://company-careers.com)",
    emailPlaceholder: "Paste recruiter email headers or email content here...",
    qrUploadText: "Drag & drop QR code image or click to upload",
    
    // Footer / FAQ
    faqTitle: "Frequently Asked Questions",
    faq1Q: "What is CyberSentinel AI?",
    faq1A: "CyberSentinel AI is an AI-powered security platform that helps students and job seekers verify if job offers, websites, emails, or QR codes are legitimate recruitment opportunities or dangerous scams.",
    faq2Q: "How does the AI detect scams?",
    faq2A: "We use advanced Google Gemini AI to analyze linguistic cues, requests for payments, sender domains, and brand mismatches, pointing out potential security threats before you share documents or money.",
    
    // Language Labels
    langSelector: "Language"
  },
  Hindi: {
    // Brand
    brandName: "साइबरसेंटिनल AI",
    tagline: "भर्ती घोटालों से एक कदम आगे रहें",
    subheading: "व्यक्तिगत जानकारी साझा करने से पहले एआई का उपयोग करके नौकरियों, इंटर्नशिप, ईमेल, वेबसाइट और क्यूआर कोड को सत्यापित करें।",
    getStarted: "शुरू करें",
    verifyNow: "अभी सत्यापित करें",
    
    // Sidebar
    navDashboard: "डैशबोर्ड",
    navJobVerify: "नौकरी सत्यापन",
    navWebVerify: "वेबसाइट सत्यापन",
    navEmailVerify: "ईमेल सत्यापन",
    navQRVerify: "क्यूआर सत्यापन",
    navAssistant: "एआई सहायक",
    navReports: "रिपोर्ट्स",
    navAnalytics: "विश्लेषण",
    navNotifications: "सूचनाएं",
    navProfile: "प्रोफ़ाइल",
    navSettings: "सेटिंग्स",
    navLogout: "लॉगआउट",
    
    // Stats
    statVerified: "अवसर सत्यापित",
    statAccuracy: "एआई पहचान सटीकता",
    statProtected: "सुरक्षित छात्र",
    
    // Dashboard Card Labels
    cardTotalScans: "कुल स्कैन",
    cardSafeReports: "सुरक्षित रिपोर्ट",
    cardHighRisk: "उच्च जोखिम रिपोर्ट",
    cardConfidence: "एआई औसत सटीकता",
    cardRecentActivity: "हाल की गतिविधि",
    cardScamAlerts: "नवीनतम घोटाला अलर्ट",
    
    // Common Actions / Fields
    analyze: "सामग्री का विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    riskScore: "जोखिम स्कोर",
    threatLevel: "खतरे का स्तर",
    threatCategory: "घोटाले की श्रेणी",
    reasons: "इसे क्यों चिह्नित किया गया?",
    recommendations: "आवश्यक सुरक्षा उपाय",
    summary: "एआई सारांश",
    confidence: "सटीकता दर",
    safe: "सुरक्षित",
    mediumRisk: "मध्यम जोखिम",
    highRisk: "उच्च जोखिम",
    
    // Modules Specifics
    jobDescPlaceholder: "नौकरी का विवरण या इंटर्नशिप प्रस्ताव पत्र का विवरण यहां पेस्ट करें...",
    webUrlPlaceholder: "कंपनी की वेबसाइट का URL पेस्ट करें (जैसे, https://company-careers.com)",
    emailPlaceholder: "भर्ती करने वाले का ईमेल या ईमेल की सामग्री यहां पेस्ट करें...",
    qrUploadText: "क्यूआर कोड की छवि खींचें और छोड़ें या अपलोड करने के लिए क्लिक करें",
    
    // Footer / FAQ
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faq1Q: "साइबरसेंटिनल AI क्या है?",
    faq1A: "साइबरसेंटिनल AI एक एआई-संचालित सुरक्षा मंच है जो छात्रों और नौकरी चाहने वालों को यह सत्यापित करने में मदद करता है कि नौकरी के प्रस्ताव, वेबसाइट, ईमेल या क्यूआर कोड वैध भर्ती के अवसर हैं या खतरनाक घोटाले।",
    faq2Q: "एआई घोटालों का पता कैसे लगाता है?",
    faq2A: "हम भाषाई संकेतों, भुगतान के अनुरोधों, प्रेषक डोमेन और ब्रांड बेमेल का विश्लेषण करने के लिए उन्नत Google जेमिनी एआई का उपयोग करते हैं, जिससे पहले कि आप दस्तावेज या पैसे साझा करें, संभावित सुरक्षा खतरों की पहचान की जा सके।",
    
    // Language Labels
    langSelector: "भाषा"
  },
  Telugu: {
    // Brand
    brandName: "సైబర్‌సెంటినెల్ AI",
    tagline: "ఉద్యోగ మోసాల కంటే ఒక అడుగు ముందే ఉండండి",
    subheading: "మీ వ్యక్తిగత సమాచారాన్ని పంచుకునే ముందు AI ని ఉపయోగించి ఉద్యోగాలు, ఇంటర్న్‌షిప్‌లు, ఈమెయిళ్ళు, వెబ్‌సైట్లు మరియు QR కోడ్‌లను ధృవీకరించండి.",
    getStarted: "ప్రారంభించండి",
    verifyNow: "ఇప్పుడే ధృవీకరించండి",
    
    // Sidebar
    navDashboard: "డాష్‌బోర్డ్",
    navJobVerify: "ఉద్యోగ ధృవీకరణ",
    navWebVerify: "వెబ్‌సైట్ ధృవీకరణ",
    navEmailVerify: "ఈమెయిల్ ధృవీకరణ",
    navQRVerify: "QR ధృవీకరణ",
    navAssistant: "AI అసిస్టెంట్",
    navReports: "రిపోర్టులు",
    navAnalytics: "విశ్లేషణలు",
    navNotifications: "నోటిఫికేషన్లు",
    navProfile: "ప్రొఫైల్",
    navSettings: "సెట్టింగులు",
    navLogout: "లాగౌట్",
    
    // Stats
    statVerified: "ధృవీకరించబడిన అవకాశాలు",
    statAccuracy: "AI గుర్తింపు ఖచ్చితత్వం",
    statProtected: "రక్షించబడిన విద్యార్థులు",
    
    // Dashboard Card Labels
    cardTotalScans: "మొత్తం స్కాన్‌లు",
    cardSafeReports: "సురక్షిత రిపోర్టులు",
    cardHighRisk: "అధిక ప్రమాద రిపోర్టులు",
    cardConfidence: "AI సగటు ఖచ్చితత్వం",
    cardRecentActivity: "ఇటీవలి కార్యాచరణ",
    cardScamAlerts: "తాజా స్కామ్ అలర్ట్‌లు",
    
    // Common Actions / Fields
    analyze: "విశ్లేషించు",
    analyzing: "విశ్లేషిస్తోంది...",
    riskScore: "ప్రమాద స్కోరు",
    threatLevel: "ముప్పు స్థాయి",
    threatCategory: "మోసం వర్గం",
    reasons: "ఎందుకు ఇది గుర్తించబడింది?",
    recommendations: "తీసుకోవాల్సిన జాగ్రత్తలు",
    summary: "AI సారాంశం",
    confidence: "గుర్తింపు ఖచ్చితత్వం",
    safe: "సురక్షితం",
    mediumRisk: "మధ్యస్థ ప్రమాదం",
    highRisk: "అధిక ప్రమాదం",
    
    // Modules Specifics
    jobDescPlaceholder: "ఉద్యోగ వివరణ లేదా ఇంటర్న్‌షిప్ లెటర్ వివరాలను ఇక్కడ పేస్ట్ చేయండి...",
    webUrlPlaceholder: "కంపెనీ వెబ్‌సైట్ URL ని ఇక్కడ పేస్ట్ చేయండి (ఉదా, https://company-careers.com)",
    emailPlaceholder: "ఈమెయిల్ కంటెంట్‌ను ఇక్కడ పేస్ట్ చేయండి...",
    qrUploadText: "QR కోడ్ చిత్రాన్ని ఇక్కడ లాగి వదలండి లేదా అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
    
    // FAQ
    faqTitle: "తరచుగా అడిగే ప్రశ్నలు",
    faq1Q: "సైబర్‌సెంటినెల్ AI అంటే ఏమిటి?",
    faq1A: "సైబర్‌సెంటినెల్ AI అనేది విద్యార్థులకు మరియు ఉద్యోగార్ధులకు ఉద్యోగ ఆఫర్లు, వెబ్‌సైట్లు, ఈమెయిళ్ళు లేదా QR కోడ్‌లు సురక్షితమైనవా లేదా మోసపూరితమైనవా అని గుర్తించడంలో సహాయపడే ఒక వినూత్న AI భద్రతా వేదిక.",
    faq2Q: "AI మోసాలను ఎలా గుర్తిస్తుంది?",
    faq2A: "మేము అధునాతన Google జెమిని AI ని ఉపయోగించి ఈమెయిల్ డొమైన్లు, డబ్బు అడిగే విధానాలు, వ్యాకరణ దోషాలు మరియు బ్రాండ్ మోసాలను విశ్लेషించి, ప్రమాదాలను ముందుగానే గుర్తిస్తాము.",
    
    langSelector: "భాష"
  },
  Tamil: {
    brandName: "சைபர்சென்டினல் AI",
    tagline: "வேலைவாய்ப்பு மோசடிகளுக்கு ஒரு படி முன்னால் இருங்கள்",
    subheading: "தனிப்பட்ட விவரங்களை பகிரும் முன் AI மூலம் வேலைகள், இன்டர்ன்ஷிப்கள், மின்னஞ்சல்கள், வலைத்தளங்கள் மற்றும் QR குறியீடுகளை சரிபார்க்கவும்.",
    getStarted: "தொடங்கவும்",
    verifyNow: "இப்போது சரிபார்க்கவும்",
    navDashboard: "டாஷ்போர்டு",
    navJobVerify: "வேலை சரிபார்ப்பு",
    navWebVerify: "வலைத்தள சரிபார்ப்பு",
    navEmailVerify: "மின்னஞ்சல் சரிபார்ப்பு",
    navQRVerify: "QR சரிபார்ப்பு",
    navAssistant: "AI உதவியாளர்",
    navReports: "அறிக்கைகள்",
    navAnalytics: "பகுப்பாய்வு",
    navNotifications: "அறிவிப்புகள்",
    navProfile: "சுயவிவரம்",
    navSettings: "அமைப்புகள்",
    navLogout: "வெளியேறு",
    statVerified: "சரிபார்க்கப்பட்ட வாய்ப்புகள்",
    statAccuracy: "AI கண்டறிதல் துல்லியம்",
    statProtected: "பாதுகாக்கப்பட்ட மாணவர்கள்",
    cardTotalScans: "மொத்த ஸ்கேன்கள்",
    cardSafeReports: "பாதுகாப்பான அறிக்கைகள்",
    cardHighRisk: "அபாயகரமான அறிக்கைகள்",
    cardConfidence: "AI சராசரி துல்லியம்",
    cardRecentActivity: "சமீபத்திய செயல்பாடு",
    cardScamAlerts: "புதிய மோசடி எச்சரிக்கைகள்",
    analyze: "பகுப்பாய்வு செய்",
    analyzing: "பகுப்பாய்வு செய்யப்படுகிறது...",
    riskScore: "அபாய மதிப்பெண்",
    threatLevel: "அபாய நிலை",
    threatCategory: "மோசடி வகை",
    reasons: "ஏன் இது குறிக்கப்பட்டது?",
    recommendations: "பாதுகாப்பு பரிந்துரைகள்",
    summary: "AI சுருக்கம்",
    confidence: "துல்லியம்",
    safe: "பாதுகாப்பானது",
    mediumRisk: "மிதமான அபாயம்",
    highRisk: "அதிக அபாயம்",
    jobDescPlaceholder: "வேலை விவரங்களை இங்கே ஒட்டவும்...",
    webUrlPlaceholder: "நிறுவனத்தின் வலைத்தள முகவரியை ஒட்டவும்...",
    emailPlaceholder: "மின்னஞ்சல் உள்ளடக்கத்தை இங்கே ஒட்டவும்...",
    qrUploadText: "QR படத்தை இங்கே இழுத்து விடவும் அல்லது பதிவேற்றவும்",
    faqTitle: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    faq1Q: "சைபர்சென்டினல் AI என்றால் என்ன?",
    faq1A: "இது மாணவர்கள் மற்றும் வேலை தேடுபவர்களுக்கு போலியான வேலைவாய்ப்பு விளம்பரங்கள் மற்றும் மோசடி மின்னஞ்சல்களை கண்டறிய உதவும் ஒரு AI பாதுகாப்பு தளமாகும்.",
    faq2Q: "AI எவ்வாறு மோசடியைக் கண்டறிகிறது?",
    faq2A: "கூகிள் ஜெமினி AI-ஐ பயன்படுத்தி, பணக் கோரிக்கைகள், போலியான மின்னஞ்சல் முகவரிகள் மற்றும் சந்தேகத்திற்கிடமான சொற்களை பகுப்பாய்வு செய்து கண்டறிகிறோம்.",
    langSelector: "மொழி"
  },
  Kannada: {
    brandName: "ಸೈಬರ್ ಸೆಂಟ್‌ನೆಲ್ AI",
    tagline: "ಉದ್ಯೋಗ ವಂಚನೆಗಳಿಗಿಂತ ಒಂದು ಹೆಜ್ಜೆ ಮುಂದಿರಿ",
    subheading: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ಹಂಚಿಕೊಳ್ಳುವ ಮುನ್ನ AI ಬಳಸಿ ಉದ್ಯೋಗಗಳು, ಇಂಟರ್ನ್‌ಶಿಪ್‌ಗಳು, ಇಮೇಲ್ ಹಾಗೂ ಕ್ಯೂಆರ್ ಕೋಡ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    verifyNow: "ಈಗಲೇ ಪರಿಶೀಲಿಸಿ",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navJobVerify: "ಉದ್ಯೋಗ ಪರಿಶೀಲನೆ",
    navWebVerify: "ವೆಬ್‌ಸೈಟ್ ಪರಿಶೀಲನೆ",
    navEmailVerify: "ಇಮೇಲ್ ಪರಿಶೀಲನೆ",
    navQRVerify: "QR ಪರಿಶೀಲನೆ",
    navAssistant: "AI ಸಹಾಯಕಿ",
    navReports: "ವರದಿಗಳು",
    navAnalytics: "ವಿಶ್ಲೇಷಣೆ",
    navNotifications: "ಸೂಚನೆಗಳು",
    navProfile: "ಪ್ರೊಫೈಲ್",
    navSettings: "ಸಂಯೋಜನೆಗಳು",
    navLogout: "ಲಾಗೌಟ್",
    statVerified: "ಪರಿಶೀಲಿಸಿದ ಅವಕಾಶಗಳು",
    statAccuracy: "AI ಪತ್ತೆ ನಿಖರತೆ",
    statProtected: "ರಕ್ಷಿತ ವಿದ್ಯಾರ್ಥಿಗಳು",
    cardTotalScans: "ಒಟ್ಟು ಸ್ಕ್ಯಾನ್‌ಗಳು",
    cardSafeReports: "ಸುರಕ್ಷಿತ ವರದಿಗಳು",
    cardHighRisk: "ಹೆಚ್ಚು ಅಪಾಯದ ವರದಿಗಳು",
    cardConfidence: "AI ಸರಾಸರಿ ನಿಖರತೆ",
    cardRecentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    cardScamAlerts: "ಇತ್ತೀಚಿನ ಹಗರಣ ಎಚ್ಚರಿಕೆಗಳು",
    analyze: "ವಿಶ್ಲೇಷಿಸಿ",
    analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    riskScore: "ಅಪಾಯದ ಅಂಕ",
    threatLevel: "ಅಪಾಯದ ಮಟ್ಟ",
    threatCategory: "ವಂಚನೆ ವರ್ಗ",
    reasons: "ಇದನ್ನು ಏಕೆ ಗುರುತಿಸಲಾಗಿದೆ?",
    recommendations: "ಸುರಕ್ಷತಾ ಶಿಫಾರಸುಗಳು",
    summary: "AI ಸಾರಾಂಶ",
    confidence: "ನಿಖರತೆ",
    safe: "ಸುರಕ್ಷಿತ",
    mediumRisk: "ಮಧ್ಯಮ ಅಪಾಯ",
    highRisk: "ಹೆಚ್ಚಿನ ಅಪಾಯ",
    jobDescPlaceholder: "ಉದ್ಯೋಗ ವಿವರಣೆಯನ್ನು ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ...",
    webUrlPlaceholder: "ವೆಬ್‌ಸೈಟ್ ಲಿಂಕ್ ಅನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ...",
    emailPlaceholder: "ಇಮೇಲ್ ವಿವರಗಳನ್ನು ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ...",
    qrUploadText: "ಕ್ಯೂಆರ್ ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಎಳೆಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    faqTitle: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    faq1Q: "ಸೈಬರ್ ಸೆಂಟ್‌ನೆಲ್ AI ಎಂದರೇನು?",
    faq1A: "ಇದು ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ ಆಧಾರಿತ ತಂತ್ರಜ್ಞಾನವಾಗಿದ್ದು, ಉದ್ಯೋಗ ಆಕಾಂಕ್ಷಿಗಳಿಗೆ ನಕಲಿ ಉದ್ಯೋಗ ಕೊಡುಗೆಗಳನ್ನು ಪತ್ತೆ ಹಚ್ಚಲು ನೆರವಾಗುತ್ತದೆ.",
    faq2Q: "ಹಗರಣಗಳನ್ನು AI ಹೇಗೆ ಪತ್ತೆ ಮಾಡುತ್ತದೆ?",
    faq2A: "ಗೂಗಲ್ ಜೆಮಿನಿ AI ಮೂಲಕ ನಕಲಿ ಇಮೇಲ್ ಐಡಿ, ನೋಂದಣಿ ಶುಲ್ಕ ಬೇಡಿಕೆ ಹಾಗೂ ಭಾಷಾ ಶೈಲಿಯನ್ನು ಪರಿಶೀಲಿಸಿ ವಂಚನೆಗಳನ್ನು ತಡೆಯುತ್ತೇವೆ.",
    langSelector: "ಭಾಷೆ"
  },
  Malayalam: {
    brandName: "സൈബർസെന്റിനൽ AI",
    tagline: "തൊഴിൽ തട്ടിപ്പുകളിൽ നിന്ന് ഒരു പടി മുന്നിൽ നിൽക്കൂ",
    subheading: "വ്യക്തിഗത വിവരങ്ങൾ പങ്കിടുന്നതിന് മുൻപ് AI ഉപയോഗിച്ച് ജോലികൾ, ഇന്റേൺഷിപ്പുകൾ, ഇമെയിലുകൾ, വെബ്‌സൈറ്റുകൾ, ക്യുആർ കോഡുകൾ എന്നിവ പരിശോധിക്കുക.",
    getStarted: "ആരംഭിക്കുക",
    verifyNow: "ഇപ്പോൾ പരിശോധിക്കുക",
    navDashboard: "ഡാഷ്‌ബോർഡ്",
    navJobVerify: "തൊഴിൽ പരിശോധന",
    navWebVerify: "വെബ്‌സൈറ്റ് പരിശോധന",
    navEmailVerify: "ഇമെയിൽ പരിശോധന",
    navQRVerify: "ക്യുആർ പരിശോധന",
    navAssistant: "AI സഹായി",
    navReports: "റിപ്പോർട്ടുകൾ",
    navAnalytics: "വിശകലനം",
    navNotifications: "അറിയിപ്പുകൾ",
    navProfile: "പ്രൊഫൈൽ",
    navSettings: "ക്രമീകരണങ്ങൾ",
    navLogout: "ലോഗ് ഔട്ട്",
    statVerified: "പരിശോധിച്ച അവസരങ്ങൾ",
    statAccuracy: "AI കണ്ടെത്തൽ കൃത്യത",
    statProtected: "സംരക്ഷിക്കപ്പെട്ട വിദ്യാർത്ഥികൾ",
    cardTotalScans: "ആകെ സ്കാനുകൾ",
    cardSafeReports: "സുരക്ഷിത റിപ്പോർട്ടുകൾ",
    cardHighRisk: "അപകടസാധ്യതയുള്ള റിപ്പോർട്ടുകൾ",
    cardConfidence: "AI ശരാശരി കൃത്യത",
    cardRecentActivity: "സമീപകാല പ്രവർത്തനങ്ങൾ",
    cardScamAlerts: "പുതിയ തട്ടിപ്പ് മുന്നറിയിപ്പുകൾ",
    analyze: "വിശകലനം ചെയ്യുക",
    analyzing: "വിശകലനം ചെയ്യുന്നു...",
    riskScore: "അപകടസാധ്യതാ സ്കോർ",
    threatLevel: "അപകടസാധ്യതാ നില",
    threatCategory: "തട്ടിപ്പ് വിഭാഗം",
    reasons: "എന്തുകൊണ്ട് ഇത് അടയാളപ്പെടുത്തി?",
    recommendations: "സുരക്ഷാ നിർദ്ദേശങ്ങൾ",
    summary: "AI ചുരുക്കം",
    confidence: "കൃത്യത",
    safe: "സുരക്ഷിതം",
    mediumRisk: "മിതമായ അപകടം",
    highRisk: "ഉയർന്ന അപകടം",
    jobDescPlaceholder: "തൊഴിൽ വിവരണം ഇവിടെ പേസ്റ്റ് ചെയ്യുക...",
    webUrlPlaceholder: "വെബ്‌സൈറ്റ് ലിങ്ക് ഇവിടെ നൽകുക...",
    emailPlaceholder: "ഇമെയിൽ വിവരങ്ങൾ ഇവിടെ പേസ്റ്റ് ചെയ്യുക...",
    qrUploadText: "ക്യുആർ ചിത്രം ഇവിടെ വലിച്ചിടുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക",
    faqTitle: "പതിവ് ചോദ്യങ്ങൾ",
    faq1Q: "എന്താണ് സൈബർസെന്റിനൽ AI?",
    faq1A: "വിദ്യാർത്ഥികൾക്കും ഉദ്യോഗാർത്ഥികൾക്കും വ്യാജ തൊഴിൽ അവസരങ്ങളും ഇമെയിലുകളും തിരിച്ചറിയാൻ സഹായിക്കുന്ന ഒരു AI സുരക്ഷാ പ്ലാറ്റ്‌ഫോമാണ് ഇത്.",
    faq2Q: "AI തട്ടിപ്പുകൾ എങ്ങനെ കണ്ടെത്തുന്നു?",
    faq2A: "ഗൂഗിൾ ജെമിനി AI ഉപയോഗിച്ച് പണ ആവശ്യങ്ങൾ, വ്യാജ ഇമെയിൽ വിലാസങ്ങൾ എന്നിവ വിശകലനം ചെയ്ത് സുരക്ഷാ ഭീഷണികൾ കണ്ടെത്തുന്നു.",
    langSelector: "ഭാഷ"
  }
};
